version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: codecraft-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: codecraft-user-service
    depends_on:
      - mongo
    environment:
      PORT: "5000"
      HOST: "0.0.0.0"
      MONGO_URI: "mongodb://mongo:27017/codecrafthub_users"
      JWT_SECRET: "change_this_in_production"
      JWT_EXPIRES_IN: "1h"
    ports:
      - "5001:5000"

volumes:
  mongo-data:
